### ISSUE TITLE
选择部分表进行备份

### ISSUE THREAD

**Issue by lotofbadcode** [lotofbadcode/phpspirit_databackup#1]
可以选择部分表进行备份

**Comment by hulang** [comment]
@lotofbadcode 自己发布问题，自己回答？怎么分表？

**Comment by hulang** [comment]
@lotofbadcode 再增加，是否备份数据，默认是，是否就只备份结构。。^_^

**Comment by lotofbadcode** [comment]
[https://github.com/lotofbadcode/phpspirit_databackup/issues/3](url)  查看此处
