### ISSUE TITLE
未定义数组索引: nowfileidex

### ISSUE THREAD

**Issue by hulang** [lotofbadcode/phpspirit_databackup#2]
在还原时报错：未定义数组索引: nowfileidex
我后台用的layui的table，比如我测试备份，是OK的，备份了几次来测试，还原。
table列表，选择其中一个还原。
    // 监听行工具事件
    table.on('tool(list)', function (obj) {
        var data = obj.data;
        if (obj.event === 'recovery') {
            recovey(data.name);
        }
    });
data.name是还原的目录，recovey函数....
// 还原
function recovey(path) {
    $.ajax({
        url: IndexUrl.recovery,
        type: 'POST',
        async: true,
        data: {
            path: path
        },
        dataType: 'json',
        success: function (json) {
            var info = '';
            if (json.totalpercentage < 100) {
                info = '正在恢复...';
            } else {
                info = '恢复完成';
            }
            //
            element.progress('mysql', json.totalpercentage + '%');
            $('#show_info').html(info);
            //
            if (json.totalpercentage < 100) {
                recovey(path);
            }
        }
    });
}
// 后台是TP
    public function recovery()
    {
        if ($this->request->isPost()) {
            $data = $this->request->post();
            //
            $backupdir = $this->backup_dir . $data['path'];
            // 构造数据库配置
            $config = $this->db['connections']['mysql'];
            $recovery = RecoveryFactory::instance('mysql', $config['hostname'] . ':' . $config['hostport'], $config['database'], $config['username'], $config['password']);
            // 还原开始
            $result = $recovery->setSqlfiledir($backupdir)->ajaxrecovery($_POST);
            return json($result);
        } else {
            $this->error('不允许非Post提交!');
        }
    }
。。。哪里错误呢？是ajax那块么？

**Comment by lotofbadcode** [comment]
recovey(path); 换 recovey(json);

https://www.kancloud.cn/lotofbadcode/php_spirit/1418990
