### ISSUE TITLE
不想备份某些表数据，只备份结构，可以加个这样的参数么？

### ISSUE THREAD

**Issue by hulang** [lotofbadcode/phpspirit_databackup#3]
自己改了，但是想作者老大写的话，可以一劳永逸，免得一更新扩展，就覆盖了。。

**Comment by lotofbadcode** [comment]
master版本已更新 可以composer update 到master 版本

->setonlystructure(true) //设置是否只备份目录结构
->settablelist(['md_menu', 'md_api_group','cmseasy_b_category']) //设置要备份的表， 默认全部表

**Comment by hulang** [comment]
@lotofbadcode 感觉作者搞反我的意思了，如我有50张表，其中5张只需要备份结构。
应该加一个参数，如上面的：->settablelist(['md_menu', 'md_api_group','cmseasy_b_category'])  // 这里的是只需要备份结构的

**Comment by lotofbadcode** [comment]
..理解错了 回头改下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "快乐浪子哥"<notifications@github.com&gt;; 
发送时间: 2020年10月15日(星期四) 上午10:14
收件人: "lotofbadcode/phpspirit_databackup"<phpspirit_databackup@noreply.github.com&gt;; 
抄送: "代码庸医"<3359964266@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lotofbadcode/phpspirit_databackup] 不想备份某些表数据，只备份结构，可以加个这样的参数么？ (#3)





 
@lotofbadcode 感觉作者搞反我的意思了，如我有50张表，其中5张只需要备份结构。
 应该加一个参数，如上面的：-&gt;settablelist(['md_menu', 'md_api_group','cmseasy_b_category'])  // 这里的是只需要备份结构的

**Comment by hulang** [comment]
@lotofbadcode 感谢作者老大，主要是有几张表，每张表6G以上了，虽然可以备份下了，但是太要时间了。。感谢作者提供的这个扩展。。从作者写的phpextend就开始使用

**Comment by lotofbadcode** [comment]
也感谢你的支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "快乐浪子哥"<notifications@github.com&gt;; 
发送时间: 2020年10月15日(星期四) 中午11:12
收件人: "lotofbadcode/phpspirit_databackup"<phpspirit_databackup@noreply.github.com&gt;; 
抄送: "代码庸医"<3359964266@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lotofbadcode/phpspirit_databackup] 不想备份某些表数据，只备份结构，可以加个这样的参数么？ (#3)





 
@lotofbadcode 感谢作者老大，主要是有几张表，每张表6G以上了，虽然可以备份下了，但是太要时间了。。感谢作者提供的这个扩展。。从作者写的phpextend就开始使用

**Comment by lotofbadcode** [comment]
@hulang  composer 更新到 master 版本
->settablelist(['md_menu', 'md_api_group','cmseasy_b_category']) //设置要备份的表， 默认全部表 
 ->setstructuretable(['md_api_group']) //设置哪些表只备份结构不备份数据

**Comment by hulang** [comment]
> @hulang composer 更新到 master 版本
> ->settablelist(['md_menu', 'md_api_group','cmseasy_b_category']) //设置要备份的表， 默认全部表
> ->setstructuretable(['md_api_group']) //设置哪些表只备份结构不备份数据

好的，老大你没有推送版本，不能更新

**Comment by lotofbadcode** [comment]
@hulang 已发布新版

**Comment by hulang** [comment]
@lotofbadcode 已更新，老大可以关闭这个帖子啊，不知道文档老大有木有更新。哈哈。

**Comment by lotofbadcode** [comment]
文档没更新呢 没来的急




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "快乐浪子哥"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 下午5:15
收件人: "lotofbadcode/phpspirit_databackup"<phpspirit_databackup@noreply.github.com&gt;; 
抄送: "代码庸医"<3359964266@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lotofbadcode/phpspirit_databackup] 不想备份某些表数据，只备份结构，可以加个这样的参数么？ (#3)





 
@lotofbadcode 已更新，老大可以关闭这个帖子啊，不知道文档老大有木有更新。哈哈。
