### ISSUE TITLE
PHP8.1下 备份报错。

### ISSUE THREAD

**Issue by hulang** [lotofbadcode/phpspirit_databackup#4]
PDO::quote(): Passing null to parameter #1 ($string) of type string is deprecated

PHP 8.0没有测试。我用的是：Laragon 6.0.0 版本。。切换到7.4没有问题

度娘一搜索上面的代码，解决方法URL：
https://www.drupal.org/project/diff/issues/3256598
我EN彩笔，不懂。。。

**Comment by lotofbadcode** [comment]
收到 等忙过这半个月修改下

**Comment by hulang** [comment]
@hulang 刚又下载了PHP 8.0 版本 扩展到Laragon 里面，>= 8.0 版本都不行。

**Comment by hulang** [comment]
@lotofbadcode 调试了下。Backup.php行319
$insertsqlv .=  $this->_pdo->quote($_v)  . ",";
改成
$insertsqlv .=  $this->_pdo->quote($_v == null ? '' : $_v)  . ",";
就行了。
